blank_issues_enabled: false
contact_links:
  - name: Ask a question / discussion
    url: https://github.com/mustafa-codez/EIS-v5.0/discussions
    about: For general questions, ideas, or discussion that isn't a bug or feature request.
